x-development-volumes: &development-volumes
  volumes:
    - ./tests:/workspace/agentric/tests/
    - ./src:/workspace/agentric/src/
    - ./Makefile:/workspace/agentric/Makefile
    - ./pyproject.toml:/workspace/agentric/pyproject.toml
    - ./uv.lock:/workspace/agentric/uv.lock
    - ./.env.docker.example:/workspace/agentric/.env
    - ./schema:/workspace/agentric/schema
    - ./schema:/workspace/agentric/team_states
    - ./templates:/workspace/agentric/templates

services:
  app:
    build:
      context: .
      dockerfile: deploy/docker/dev/Dockerfile
    ports:
      - "8023:8000"
      - "3006:3006"
    tty: true
    environment:
      VITE_USE_SERVER_LIFESPAN: "true" # true in dev or run
      VITE_DEV_MODE: "true"
      VITE_HOT_RELOAD: "true"
      SAQ_USE_SERVER_LIFESPAN: "false"
    command: litestar run --reload --host 0.0.0.0 --port 8000
    restart: always
    <<: *development-volumes
  worker:
    build:
      context: .
      dockerfile: deploy/docker/dev/Dockerfile
    command: litestar workers run
    tty: true

    restart: always
    <<: *development-volumes
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

    env_file:
      - .env.docker.example
    volumes:
      - ./schema:/workspace/agentric/schema
  migrator:
    build:
      context: .
      dockerfile: deploy/docker/dev/Dockerfile
    command: litestar database upgrade --no-prompt
    # command: sh -c "sleep 3 && litestar database upgrade --no-prompt"
    restart: "no"
    <<: *development-volumes
    env_file:
      - .env.docker.example
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
